name: CI Pipeline

on:
  push:
    branches: [ main, phase-1, phase-2, phase-3 ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu indir
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Kodun çalışıp çalışmadığını kontrol et
        run: |
          cd src
          python servis.py